---
title: "Xiangyi Shan BIS557 HW4"
author: "Xiangyi Shan"
date: "12/4/2018"
output: html_document
---

##1. CASL Number 2 in Exercises 5.8.
```{r}
#Generate a matrix X
X <- matrix(c(1, 1, 2, 0.3), nrow=2, ncol=2)

#Generate a propabilities p
p <- c(0.0000001, 0.1)

#According to textbook p27, calculate the condition number for X'X
s <- t(X) %*% X
svals <- svd(s)$d
max(svals)/min(svals)

#Calculate the condition number for logistic variation
var <- diag(p*(1-p))
H <- t(X) %*% var %*% X
svals_H <- svd(H)$d
max(svals_H)/min(svals_H)

#Conclusion:The conditional number for X'X is very small comparing to that of logistic variation. Therefore, X'X is a well-condition matrix but its logistic variation not.
```

##2. CASL Number 4 in Exercises 5.8.
```{r}
#According to the textbook p129 coding

# X: A numeric data matrix.
# y: Response vector.
# family: Instance of an R 'family' object
# maxit: Integer maximum number of iterations.
# tol: Numeric tolerance parameter.
irwls_glm <- 
function(X, y, family, maxit=25, tol=1e-10, lambda)
{
  beta <- rep(0,ncol(X))
  for(j in 1:maxit)
  {
    b_old <- beta
    eta <- X %*% beta
    mu <- family$linkinv(eta)
    mu_p <- family$mu.eta(eta)
    z <- eta + (y - mu) / mu_p
    W <- as.numeric(mu_p^2 / family$variance(mu))
    XtX <- crossprod(X, diag(W) %*% X)
    Xtz <- crossprod(X, W * z)
    beta <- solve(XtX + diag(lambda, dim(XtX)[1]), Xtz) #insert l2 norm
    if(sqrt(crossprod(beta - b_old)) < tol) break
  }
  beta
}
```